Python/binomial_expansion_series.py
Added python program to print binomial expansion series
=> Added binomial expansion series

Python/Login Form
Hey it's the fellow Python coder again, This time I've submitted a login form that uses the tkinter module to input name, phone number, gender, emergency and payment mode. It works like an actual form and I hope you find it useful. Cheers! 
P.S.-Thanks a lot for suggesting this repo, I hope this program can make it up to you :)
=> Login Form

Python/Hand_Cricket.py
This is game of Hand Cricket 🏏 made in python
=> Hand Cricket Game

JavaScript/Star-Rating-Website/index.html, JavaScript/Star-Rating-Website/readme.md, JavaScript/Star-Rating-Website/script.js, JavaScript/Star-Rating-Website/style.css
This website fetches images using API, stores your rating and uses HTML, CSS and JS for front-end
=> Added a Image Rating Website made using HTML, CSS, JS to the JavaScript folder

Java/Fibonacci_series.java
Added Fibonacci series in Java program
=> Fibonacci series in java

Python/Detector.py, Python/haarcascade_frontalface_default.xml
This program can be used to detect motion and faces within the camera's frame.
=> Motion and Face Detection

Flask/main.py, Flask/templates/signup.html
Creating a Flask App .
If any one wants to contribute please create a login page with API
=> Added SignUp Page

Python/Youtube Downloader
Hey
I have made a commit with the name **"Added YoutubeDownloader"** with respect to HacktoberFest 2022
Please see If you can merge the PR
=> Added YoutubeDownloader

Java/How to Generate Random Number in Java
Hi I am Kabir Mittal and I am an computer science and engineering student
=> Generating Random Number in Java

Python/authentication.py
Python program which serves the following functions for authentication:
- Create a new account using username and password.
- Sign-in with pre-existing account
- Check if username already exists
- Terminates the program
=> Add authentication via Python

Java/FordFulkersonAlgorithm.java
Added an important algorithm for contribution in this hacktoberfest season
=> Added Ford Fulkerson Algorithm

Java/palindrome.java
added palindrome number checker java program
=> create palindrome number checker

Java/DijkstraAlgorithm.java
Added an important algorithm ,Dijkstra's Algorithm that is helpful in the DSA journey, as a contribution during this Hacktoberfest season
=> Added Dijkstra's Algorithm

Python/Hirst Dot Painting.py
I made this Python file opt to be useful for drawing, hope you like it... if you did, please merge it and give me the hacktoberfest-accepted label, thank you.. regards, @007lakshya
=> Create Hirst Dot Painting.py

JavaScript/Calculator.js
=> Added new files and minor changes

JavaScript/Calculator.js, Python/PyPassword Generator.py
Hi, Please check this pr, Hope you like it..
=> New minor Changes

Java/PrimsAlgo.java
Added a java file of Prim's Algorithm that is an important algorithm for competitive coding
=> Create Prim's Algorithm

Python/funGames.py
Three popular games among teenagers added via Python.
The following games are added:
1. Truth or Dare
2. Would You Rather
3. Never Have I ever
Main points to note: 
- Quick and Responsive
- API-based process
- Algorithmic Approach 
- Easy-bug detection and program termination.
**MADE WITH LOVE <3**
=> Three playable games via Python

Java/quickSort.java
The quick sort in most optimized manner. Please, accept the pull request for Hacktoberfest 2022.
=> Quick Sort in Java

Python/avengers.py
Created a avengers superhero name guess game using python where you have 10 tries to guess the name of the avengers.
=> avengersNameGuess

C++/AnagramCheck.cpp
Added Anagram Check in C++ Programs which checks whether two strings are anagram(Containing the Same number of alphabets of same kind) or not
=> Added AnagramCheck

JavaScript/CRUD Project/CRUD Project/index.html, JavaScript/CRUD Project/CRUD Project/script.js, JavaScript/CRUD Project/CRUD Project/style.css
=> Added CRUD Project using js

C++/sum_of_n_natural_number_O(1).cpp
I have resolved this issue:  [Click here](https://github.com/Idhant-6/Hacktoberfest-2022/issues/63)
Hope You Like,
Thanks
=> Sum of n natural number in O(1)

Java/CheckDisjointArrays.java
@Idhant-6 I have added a code to check 2 Arrays are disjoint or not.
=> Check Two Arrays are Disjoint or Not

Python/Insertion sort algorithm/README.md, Python/Insertion sort algorithm/insertion_sort_algorithm.py
Sorting and Searching algorithms like insertion sort, selection sort, merge sort are very important to learn as a part of the preparation of your placements and also for internships because these form the base of any programmer. As a programmer, you have to deal with large amounts of data. Hence, we use sorting algorithms and one of them is an insertion sort. Now, the Insertion sort algorithm is a comparison-based sorting algorithm in which the sorted array is built by inserting one element at its correct position at a time.
=> Create Insertion Sort Algorithm in Data Structures using Python

C++/height_bt.cpp
=> height of a binary tree

C++/zig_zag_traversal.cpp
Added zig zag traversal of a tree
=> zig zag traversal of a tree

HTML/Digital_clock/README.md, HTML/Digital_clock/index.css, HTML/Digital_clock/index.html, HTML/Digital_clock/index.js
Added Digital Clock Project. Kindly review it and merge it with hacktoberfest-accepted label @Idhant-6
=> Added Digital Clock
